services:
  - type: web
    name: resolutionpal
    env: python
    buildCommand: npm install && npm run build:css && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_RUN_PORT
        value: 10000 