services:
  - type: web
    name: resolutionpal
    env: python
    buildCommand: npm install && npm run build:css && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind=0.0.0.0:$PORT --worker-class=gthread --workers=1 --threads=4 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000