services:
  - type: web
    name: resolutionpal
    env: python
    buildCommand: |
      rm -rf .venv
      python -m venv .venv
      . .venv/bin/activate
      npm install && npm run build:css && pip install -r requirements.txt
      # Remove any existing Gunicorn configs
      find / -name "gunicorn.conf.py" -delete 2>/dev/null || true
      find / -name "gunicorn.config.py" -delete 2>/dev/null || true
    startCommand: |
      # Print Python and Gunicorn versions
      python --version
      gunicorn --version
      # Start with our config file
      gunicorn -c .gunicorn.conf.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"