services:
  - type: web
    name: resolutionpal
    env: python
    buildCommand: |
      rm -rf .venv
      python -m venv .venv
      . .venv/bin/activate
      npm install && npm run build:css && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000